#!/bin/bash

# Reconnect WireGuard if not connected.

# (c) 2025, drmats
# Licensed under the Apache License, Version 2.0

# crontab -e
# */1 * * * * /root/scripts/wgreconnect




# ...
main () {
    peers=$(wg | grep peer)
    peers_present=$?
    if [ "$peers_present" != "0" ]; then
        systemctl restart wginit
    fi
}

# ...
main
