#!/bin/bash

# Bulk chmod all files in the current directory
# (and, recursively, in all descendant sub-directories).

# (c) 2018, drmats
# Licensed under the Apache License, Version 2.0




if [ $# -ne 1 ]
then
    echo "Usage: $(basename $0) MODE"
    exit 2
fi

find . -type f -exec chmod $1 '{}' \;
