#!/bin/bash

# Bulk chown all files and directories in the current directory
# (and, recursively, in all descendant sub-directories).

# (c) 2018, drmats
# Licensed under the Apache License, Version 2.0




if [ $# -ne 2 ]
then
    echo "Usage: $(basename $0) OWNER GROUP"
    exit 2
fi

find . -mindepth 1 -exec chown -hv $1:$2 '{}' \;
